import { User, Report, DashboardStats } from "./types";

export const mockUsers: User[] = [
  {
    id: "1",
    name: "John Doe",
    email: "john@example.com",
    role: "reporter",
  },
  {
    id: "2",
    name: "Admin User",
    email: "admin@example.com",
    role: "admin",
  },
];

export const mockReports: Report[] = [
  {
    id: "RPT-001",
    reporter: {
      id: "1",
      name: "John Doe",
      email: "john@example.com",
      phone: "081234567890",
      address: "Jakarta, Indonesia",
    },
    title: "Phishing Email from Fake Bank",
    description:
      "Received an email pretending to be from Bank Mandiri asking to verify account details. The email contains suspicious links leading to a fake banking website.",
    crimeType: "phishing",
    incidentDate: "2025-01-15",
    incidentTime: "14:30",
    location: "Email",
    evidenceFiles: [
      {
        id: "1",
        name: "phishing-email.png",
        type: "image/png",
        size: 245000,
        url: "#",
      },
    ],
    relatedUrls: ["https://fake-bank-example.com/verify"],
    status: "received",
    createdAt: "2025-01-15T14:30:00Z",
    updatedAt: "2025-01-15T14:30:00Z",
  },
  {
    id: "RPT-002",
    reporter: {
      id: "1",
      name: "John Doe",
      email: "john@example.com",
      phone: "081234567890",
      address: "Jakarta, Indonesia",
    },
    title: "Unauthorized Transaction on Credit Card",
    description:
      "Found unauthorized transactions on my credit card totaling Rp 5,000,000. I did not make these purchases and suspect my card details were stolen.",
    crimeType: "online_fraud",
    incidentDate: "2025-01-14",
    incidentTime: "09:15",
    location: "Online Shopping Platform",
    evidenceFiles: [],
    relatedUrls: [],
    status: "in_progress",
    createdAt: "2025-01-14T09:15:00Z",
    updatedAt: "2025-01-16T10:00:00Z",
    adminNotes: "Investigating with bank fraud department",
  },
  {
    id: "RPT-003",
    reporter: {
      id: "1",
      name: "Jane Smith",
      email: "jane@example.com",
      phone: "085678901234",
      address: "Surabaya, Indonesia",
    },
    title: "Ransomware Attack on Company Server",
    description:
      "Our company server was infected with ransomware. All files are encrypted and a ransom note demands payment in Bitcoin to decrypt them.",
    crimeType: "ransomware",
    incidentDate: "2025-01-13",
    incidentTime: "03:00",
    location: "Company Office Server",
    evidenceFiles: [
      {
        id: "2",
        name: "ransom-note.txt",
        type: "text/plain",
        size: 1200,
        url: "#",
      },
      {
        id: "3",
        name: "encrypted-files-list.pdf",
        type: "application/pdf",
        size: 89000,
        url: "#",
      },
    ],
    relatedUrls: [],
    status: "completed",
    createdAt: "2025-01-13T03:00:00Z",
    updatedAt: "2025-01-18T16:45:00Z",
    adminNotes: "Resolved. Backup restored. Security patches applied.",
  },
  {
    id: "RPT-004",
    reporter: {
      id: "1",
      name: "Bob Wilson",
      email: "bob@example.com",
      phone: "087890123456",
      address: "Bandung, Indonesia",
    },
    title: "Social Media Account Hacked",
    description:
      "My Instagram account was hacked. The hacker changed the password and email, and is posting spam content from my account.",
    crimeType: "identity_theft",
    incidentDate: "2025-01-12",
    incidentTime: "20:00",
    location: "Instagram",
    evidenceFiles: [],
    relatedUrls: ["https://instagram.com/myaccount"],
    status: "received",
    createdAt: "2025-01-12T20:00:00Z",
    updatedAt: "2025-01-12T20:00:00Z",
  },
  {
    id: "RPT-005",
    reporter: {
      id: "1",
      name: "Alice Brown",
      email: "alice@example.com",
      phone: "089012345678",
      address: "Yogyakarta, Indonesia",
    },
    title: "DDoS Attack on E-commerce Website",
    description:
      "Our e-commerce website experienced a DDoS attack that took it offline for 6 hours. The attack flooded our servers with millions of requests.",
    crimeType: "ddos",
    incidentDate: "2025-01-11",
    incidentTime: "10:30",
    location: "Company Website",
    evidenceFiles: [
      {
        id: "4",
        name: "server-logs.txt",
        type: "text/plain",
        size: 5600000,
        url: "#",
      },
    ],
    relatedUrls: [],
    status: "in_progress",
    createdAt: "2025-01-11T10:30:00Z",
    updatedAt: "2025-01-15T14:20:00Z",
    adminNotes: "Analyzing attack patterns. IP addresses logged.",
  },
  {
    id: "RPT-006",
    reporter: {
      id: "1",
      name: "Charlie Davis",
      email: "charlie@example.com",
      phone: "081123456789",
      address: "Medan, Indonesia",
    },
    title: "Malware Infection on Personal Computer",
    description:
      "My computer was infected with malware after downloading a cracked software. The malware is stealing my passwords and browser data.",
    crimeType: "malware",
    incidentDate: "2025-01-10",
    incidentTime: "16:45",
    location: "Personal Computer",
    evidenceFiles: [],
    relatedUrls: [],
    status: "completed",
    createdAt: "2025-01-10T16:45:00Z",
    updatedAt: "2025-01-14T09:30:00Z",
    adminNotes: "System cleaned. Recommended antivirus installation.",
  },
  {
    id: "RPT-007",
    reporter: {
      id: "1",
      name: "Diana Evans",
      email: "diana@example.com",
      phone: "082234567890",
      address: "Semarang, Indonesia",
    },
    title: "Data Breach at Online Store",
    description:
      "I received notification that my personal data (name, address, phone, credit card) was leaked in a data breach from an online store I used.",
    crimeType: "data_breach",
    incidentDate: "2025-01-09",
    incidentTime: "08:00",
    location: "Online Store Database",
    evidenceFiles: [
      {
        id: "5",
        name: "breach-notification.pdf",
        type: "application/pdf",
        size: 45000,
        url: "#",
      },
    ],
    relatedUrls: [],
    status: "rejected",
    createdAt: "2025-01-09T08:00:00Z",
    updatedAt: "2025-01-12T11:00:00Z",
    adminNotes: "Report filed to the online store. No criminal intent found.",
  },
  {
    id: "RPT-008",
    reporter: {
      id: "1",
      name: "Frank Green",
      email: "frank@example.com",
      phone: "083345678901",
      address: "Malang, Indonesia",
    },
    title: "Cyberstalking via Social Media",
    description:
      "Someone has been creating fake profiles using my photos and sending harassing messages to my contacts. This has been ongoing for 2 weeks.",
    crimeType: "cyberstalking",
    incidentDate: "2025-01-08",
    incidentTime: "22:00",
    location: "Facebook & Twitter",
    evidenceFiles: [
      {
        id: "6",
        name: "harassing-messages.zip",
        type: "application/zip",
        size: 1200000,
        url: "#",
      },
    ],
    relatedUrls: ["https://facebook.com/fakeprofile123"],
    status: "in_progress",
    createdAt: "2025-01-08T22:00:00Z",
    updatedAt: "2025-01-14T15:30:00Z",
    adminNotes: "Coordinating with social media platform for profile removal.",
  },
];

export const mockDashboardStats: DashboardStats = {
  totalReports: 8,
  received: 2,
  inProgress: 3,
  completed: 2,
  rejected: 1,
  reportsByType: [
    { type: "Phishing", count: 1 },
    { type: "Online Fraud", count: 1 },
    { type: "Ransomware", count: 1 },
    { type: "Identity Theft", count: 1 },
    { type: "DDoS", count: 1 },
    { type: "Malware", count: 1 },
    { type: "Data Breach", count: 1 },
    { type: "Cyberstalking", count: 1 },
  ],
  reportsByMonth: [
    { month: "Aug", count: 3 },
    { month: "Sep", count: 5 },
    { month: "Oct", count: 4 },
    { month: "Nov", count: 7 },
    { month: "Dec", count: 6 },
    { month: "Jan", count: 8 },
  ],
};
